### ISSUE TITLE
default user and password?

### ISSUE THREAD

**Issue by ghost** [franciscoluiz/ExtDesk#4]
can you give me "default user and password." ?

using md5 or password or sha or etc ? ....

**Comment by xcape** [comment]
xcape, demos
francisco, demos

**Comment by xcape** [comment]
xcape, demos
francisco, demos...

welcome to extdesk... more news soon.

2012/1/29 panega <
reply@reply.github.com

> can you give me "default user and password." ?
> 
> using md5 or password or sha or etc ? ....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/franciscoluiz/ExtDesk/issues/4

## 

... y en la sombra, muere el genio, sin saber de su magia concebida mucho
tiempo antes de nacer.

**Comment by ghost** [comment]
ok thanks..
