### ISSUE TITLE
Login screen shows a wrong message if the database config it's incorrect

### ISSUE THREAD

**Issue by arianmaykon** [franciscoluiz/ExtDesk#5]
If you configurate the database connection incorrectly you'll get a message:

"Usuario y contraseña incorrectos, desea intentar nuevamente"

while in the json return of the request a message is shown with the connection problem.

Example:
 {"success":false,"error":"0","msg":"SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"}

**Comment by xcape** [comment]
Votado...!!

**Comment by xcape** [comment]
Fixed Broh...

https://github.com/franciscoluiz/ExtDesk/commit/6d546276ba55694b04f997d4e2842c7f32675089
